import { useEffect, useState } from "react";
import { get, post, errorText } from "./api";
import AssessmentCameraReview from "./AssessmentCameraReview";

export default function AssessmentManager({ course, onSource }) {
  const [topicId, setTopicId] = useState(course.topics[0]?.id || ""), [kind, setKind] = useState("quiz"), [prompt, setPrompt] = useState(""), [title, setTitle] = useState(""), [difficulty, setDifficulty] = useState(1), [language, setLanguage] = useState(course.language), [options, setOptions] = useState(["", "", "", ""]), [correct, setCorrect] = useState(0), [tests, setTests] = useState('[{"input":"","expected":""}]'), [starter, setStarter] = useState(""), [solution, setSolution] = useState(""), [sources, setSources] = useState(""), [bank, setBank] = useState([]), [vivas, setVivas] = useState([]), [revision, setRevision] = useState(0), [busy, setBusy] = useState(false), [error, setError] = useState("");
  const [accepted, setAccepted] = useState(""), [number, setNumber] = useState(""), [tolerance, setTolerance] = useState(0), [explanation, setExplanation] = useState(""), [reviews, setReviews] = useState([]);
  useEffect(() => { let active = true; get(`courses/${course.id}/assessment-review/`).then(data => { if (active) setReviews(data.attempts); }).catch(err => { if (active) setError(errorText(err)); }); return () => { active = false; }; }, [course.id, revision]);
  useEffect(() => { setTopicId(course.topics[0]?.id || ""); setLanguage(course.language); }, [course.id, course.topics, course.language]);
  useEffect(() => { let active = true; setBank([]); if (topicId) get(`topics/${topicId}/bank/`).then(data => { if (active) setBank(data.questions); }).catch(err => { if (active) setError(errorText(err)); }); return () => { active = false; }; }, [topicId, revision]);
  useEffect(() => { let active = true; get(`courses/${course.id}/viva-review/`).then(data => { if (active) setVivas(data.answers); }).catch(err => { if (active) setError(errorText(err)); }); return () => { active = false; }; }, [course.id, revision]);
  async function create(event) {
    event.preventDefault(); setBusy(true); setError("");
    try { await post(`topics/${topicId}/bank/`, { title, kind, prompt, difficulty: Number(difficulty), language, options: options.filter(o => o.trim()), answer: kind === "numerical" ? { value: number, tolerance } : kind === "short_answer" ? { accepted: accepted.split("\n").filter(a => a.trim()) } : { correct_index: Number(correct) }, explanation, tests: kind === "code" ? JSON.parse(tests) : [], starter_code: starter, solution, source_ids: sources ? sources.split(",").map(Number) : [] }); setPrompt(""); setTitle(""); setRevision(v => v + 1); }
    catch (err) { setError(err instanceof SyntaxError ? "Hidden tests must be valid JSON." : errorText(err)); } finally { setBusy(false); }
  }
  return <><AssessmentCameraReview course={course} onSource={onSource} /><section className="classroomBox"><p className="eyebrow">TEACHER-CONTROLLED ASSESSMENTS</p><h2>Adaptive question bank</h2><p>LabTwin selects these questions by topic, prerequisite need and difficulty. Answer keys, solutions and hidden tests stay on the server.</p><form onSubmit={create}><div className="compactForm"><label>Assessment topic<select aria-label="Assessment topic" required value={topicId} onChange={e => setTopicId(e.target.value)}><option value="">Choose topic</option>{course.topics.map(topic => <option key={topic.id} value={topic.id}>{topic.name}</option>)}</select></label><label>Question type<select aria-label="Question type" value={kind} onChange={e => setKind(e.target.value)}><option value="quiz">MCQ</option><option value="short_answer">Short answer</option><option value="numerical">Numerical</option><option value="code">Programming</option></select></label><label>Difficulty<select aria-label="Difficulty" value={difficulty} onChange={e => setDifficulty(e.target.value)}><option value="1">1 · Foundation</option><option value="2">2 · Application</option><option value="3">3 · Challenge</option></select></label></div><label>Assessment title<input required value={title} onChange={e => setTitle(e.target.value)} maxLength={200} /></label><label>Question prompt<textarea required value={prompt} onChange={e => setPrompt(e.target.value)} /></label>
      {kind === "quiz" ? <><div className="classroomColumns">{options.map((option, i) => <label key={i}>Option {i + 1}<input required value={option} onChange={e => setOptions(previous => previous.map((v, index) => index === i ? e.target.value : v))} /></label>)}</div><label>Correct answer<select aria-label="Correct answer" value={correct} onChange={e => setCorrect(e.target.value)}>{options.map((_, index) => <option key={index} value={index}>Option {index + 1}</option>)}</select></label></> : kind === "short_answer" ? <label>Accepted answer examples (one per line)<textarea required value={accepted} onChange={e => setAccepted(e.target.value)} /></label> : kind === "numerical" ? <div className="compactForm"><label>Expected numerical value<input required type="number" step="any" value={number} onChange={e => setNumber(e.target.value)} /></label><label>Absolute tolerance<input type="number" min="0" step="any" value={tolerance} onChange={e => setTolerance(e.target.value)} /></label></div> : <><label>Language<select aria-label="Assessment language" value={language} onChange={e => setLanguage(e.target.value)}>{["Python", "C", "Java"].map(l => <option key={l}>{l}</option>)}</select></label><label>Starter code<textarea className="codeEditor" value={starter} onChange={e => setStarter(e.target.value)} /></label><label>Hidden tests JSON<textarea required value={tests} onChange={e => setTests(e.target.value)} /></label><label>Teacher solution (optional)<textarea className="codeEditor" value={solution} onChange={e => setSolution(e.target.value)} /></label></>}
      <label>Feedback explanation<textarea value={explanation} onChange={e => setExplanation(e.target.value)} /></label><details><summary>Attach source references</summary><label>Source chunk IDs, separated by commas<input value={sources} onChange={e => setSources(e.target.value)} placeholder="12, 19, 24" /></label><p>Source IDs appear in citation URLs (#source=ID). All references must belong to this course.</p></details><button disabled={busy || !topicId}>{busy ? "Saving assessment…" : "Add assessment"}</button>{error && <p role="alert">{error}</p>}</form>
      <h3>Questions for this topic</h3>{bank.map(item => <details key={item.id}><summary>{item.title} · {item.kind} · Level {item.difficulty}</summary><p>{item.prompt}</p>{item.kind === "code" ? <pre>{JSON.stringify(item.tests, null, 2)}</pre> : <p>Answer key: {item.kind === "quiz" ? `option ${item.answer.correct_index + 1}` : item.kind === "numerical" ? item.answer.value : item.answer.accepted?.join(" / ")}</p>}</details>)}{!bank.length && <p>No teacher-authored assessments for this topic. Source-based quiz generation remains available when materials exist.</p>}
    </section><section className="classroomBox"><h2>Short-answer review</h2><p>Open-ended responses need teacher judgment before they affect mastery.</p>{reviews.map(attempt => <ShortReview key={attempt.id} attempt={attempt} onSaved={() => setRevision(v => v + 1)} />)}{!reviews.length && <p>No responses awaiting review.</p>}</section><section className="classroomBox"><h2>Adaptive viva review</h2><p>Review saved answers and revise provisional AI estimates.</p>{vivas.map(turn => <VivaReview key={turn.id} turn={turn} onSaved={() => setRevision(v => v + 1)} />)}{!vivas.length && <p>No adaptive viva sessions yet.</p>}</section></>;
}

function VivaReview({ turn, onSaved }) {
  const [score, setScore] = useState(turn.score ?? ""), [feedback, setFeedback] = useState(turn.feedback), [error, setError] = useState("");
  async function review(event) { event.preventDefault(); try { await post(`viva-turns/${turn.id}/review/`, { score, feedback }); onSaved(); } catch (err) { setError(errorText(err)); } }
  return <details><summary>{turn.student} · {turn.topic} · {turn.score ?? "Awaiting answer"}{turn.assessment_mode === "teacher_reviewed" ? " · Teacher reviewed" : " · Provisional"}</summary><h3>{turn.question}</h3><p className="sourceText">{turn.answer || "Not answered yet"}</p>{turn.verification && <p>A fresh conceptual verification question was offered. Activity observations are not proof of misconduct.</p>}{turn.score != null && <form onSubmit={review}><label>Reviewed viva score<input type="number" min={0} max={100} step="0.1" required value={score} onChange={e => setScore(e.target.value)} /></label><label>Viva feedback<textarea value={feedback} onChange={e => setFeedback(e.target.value)} /></label><button>Save viva review</button>{error && <p role="alert">{error}</p>}</form>}</details>;
}

function ShortReview({ attempt, onSaved }) {
  const [score, setScore] = useState(""), [feedback, setFeedback] = useState(attempt.explanation || ""), [error, setError] = useState("");
  async function review(event) { event.preventDefault(); try { await post(`practice-attempts/${attempt.id}/review/`, { score, feedback }); onSaved(); } catch (err) { setError(errorText(err)); } }
  return <details><summary>{attempt.student} · {attempt.question}</summary><p>{attempt.answer}</p><p>Answer examples: {attempt.accepted.accepted?.join(" / ")}</p><form onSubmit={review}><label>Reviewed score<input required type="number" min="0" max="100" value={score} onChange={e => setScore(e.target.value)} /></label><label>Feedback<textarea value={feedback} onChange={e => setFeedback(e.target.value)} /></label><button>Save answer review</button>{error && <p role="alert">{error}</p>}</form></details>;
}
