import { useEffect, useState } from "react";
import api, { API } from "../api";
import { get, post, errorText } from "./api";
import SourceLinks from "./SourceLinks";
import { CoachingPanel } from "./PracticeWorkspace";
import TeacherInsights from "./TeacherInsights";
import EvaluationDashboard from "./EvaluationDashboard";

const steps = ["Open a classroom", "Upload PDF + slides + video", "Extract text + figures + topics + timestamps", "Ask a course question", "Open exact source citations", "Ask an off-material question", "Decline unsupported information", "Start an adaptive assessment", "Inspect source / difficulty / verification", "Make a conceptual coding mistake", "Get cited progressive hints", "Update the learner model", "Generate a personalized follow-up", "Why am I getting this question?", "Retry and improve", "Inspect teacher improvement evidence", "Run evaluation and inspect real metrics"];

export default function DemoPanel({ teacher, onSource, onPreview, onReturnTeacher, refresh }) {
  const [demo, setDemo] = useState(null), [enabled, setEnabled] = useState(false), [answer, setAnswer] = useState(null), [attempt, setAttempt] = useState(null), [code, setCode] = useState(""), [followup, setFollowup] = useState(null), [followupCode, setFollowupCode] = useState(""), [followupResult, setFollowupResult] = useState(null), [busy, setBusy] = useState(false), [error, setError] = useState(""), [revision, setRevision] = useState(0);
  const [offAnswer, setOffAnswer] = useState(null), [assessment, setAssessment] = useState(null), [quizAnswer, setQuizAnswer] = useState(""), [quizResult, setQuizResult] = useState(null);
  const [figureAnswer, setFigureAnswer] = useState(null);
  useEffect(() => { let active = true; get("demo/").then(data => { if (active) { setEnabled(data.enabled); setDemo(data.demo); } }).catch(err => { if (active) setError(errorText(err)); }); return () => { active = false; }; }, [teacher]);
  const updateDemo = async () => { const data = await get("demo/"); setDemo(data.demo); };
  async function action(operation) { setBusy(true); setError(""); try { await operation(); await updateDemo(); setRevision(v => v + 1); refresh(); } catch (err) { setError(errorText(err)); } finally { setBusy(false); } }
  return <><section className="classroomBox demoPanel"><p className="eyebrow">TRACK D · PERSONALIZED TUTORING & ADAPTIVE LEARNING</p><h2>Hackathon Demo Mode</h2><p>Follow one learner from grounded explanation to a coding mistake, targeted coaching and measurable improvement.</p><ol className="demoSteps">{steps.map((step, index) => <li key={step} className={demo?.detailed_progress?.[index] ? "complete" : ""}><span>{demo?.detailed_progress?.[index] ? "✓" : index + 1}</span>{step}</li>)}</ol>
    {!enabled && <p>Demo mode is disabled on this server. Set LABTWIN_DEMO_ENABLED=true to enable the isolated demo classroom.</p>}{error && <p role="alert">{error}</p>}
    {teacher && !demo && <button disabled={busy || !enabled} onClick={() => action(async () => { const data = await post("demo/"); setDemo(data.demo); })}>{busy ? "Processing three demo materials…" : "Prepare guided demo"}</button>}
    {demo && <><p className="methodNote">{demo.mode_note}</p><div className="materialGrid">{demo.materials.map(material => <div className="materialCard" key={material.id}><span className="materialKind">{material.kind}</span><strong>{material.title}</strong><p>{material.status} · {material.unit_count} source sections</p>{material.error && <p role="alert">{material.error}</p>}</div>)}</div></>}
    {teacher && demo && <button disabled={busy || demo.materials.some(m => m.status !== "ready")} onClick={() => action(async () => { const data = await post(`demo/${demo.id}/student/`); await onPreview(data); })}>Enter isolated student demo</button>}
    {teacher && demo?.materials.some(m => m.status === "failed") && <button disabled={busy} onClick={() => action(async () => { await post("demo/"); })}>Retry demo processing</button>}
    {!teacher && demo && <>
      <section className="demoStage"><h3>1. Ask your course</h3><p>“How do I insert at the beginning of a linked list?”</p><button disabled={busy} onClick={() => action(async () => { setAnswer(await post(`courses/${demo.course.id}/ask/`, { question: "Explain insertion at the beginning of a linked list" })); })}>Ask demo question</button>{answer && <article className="answerCard"><p className="sourceText">{answer.answer}</p><SourceLinks items={answer.citations} onSource={onSource} /></article>}</section>
      <section className="demoStage"><h3>Source boundaries & visual understanding</h3><button disabled={busy} onClick={() => action(async () => { setFigureAnswer(await post(`courses/${demo.course.id}/ask/`, { question: "Explain the diagram on slide 2", material_id: demo.materials.find(m => m.kind === "slides").id })); })}>Explain demo diagram</button>{figureAnswer && <article className="answerCard"><p>{figureAnswer.answer}</p><SourceLinks items={figureAnswer.citations} onSource={onSource} /></article>}<button className="secondary" disabled={busy} onClick={() => action(async () => { setOffAnswer(await post(`courses/${demo.course.id}/ask/`, { question: "Explain quantum teleportation" })); })}>Ask off-material question</button>{offAnswer && <p className="practiceResult">{offAnswer.answer}</p>}</section>
      <section className="demoStage"><h3>Adaptive source-based assessment</h3>{!assessment && <button disabled={busy} onClick={() => action(async () => { const data = await post(`courses/${demo.course.id}/assessments/`, { kind: "diagnostic", scope: { topic_ids: [demo.topic_id] }, formats: ["quiz"], count: 1 }); setAssessment(data.assessment); })}>Start demo assessment</button>}{assessment && <><p className="statusTag">{assessment.questions[0].topic} · Difficulty {assessment.questions[0].difficulty}/3 · {assessment.questions[0].verification.status}</p><h4>{assessment.questions[0].prompt}</h4><SourceLinks items={assessment.questions[0].resources} onSource={onSource} /><details><summary>Why this assessment question?</summary><p>{assessment.questions[0].reason}</p><p>Verification: {assessment.questions[0].verification.method}</p></details>{assessment.questions[0].options.map((option, index) => <label className="quizOption" key={index}><input type="radio" name="demo-quiz" value={index} checked={quizAnswer === String(index)} onChange={e => setQuizAnswer(e.target.value)} /><span>{option}</span></label>)}<button disabled={busy || quizAnswer === "" || !!quizResult} onClick={() => action(async () => { setQuizResult(await post(`questions/${assessment.questions[0].id}/attempts/`, { request_id: crypto.randomUUID(), answer: quizAnswer })); })}>Submit demo assessment</button>{quizResult && <div className="practiceResult"><p>Assessment score: {quizResult.attempt.score}% · Mastery estimate {quizResult.mastery?.score}%</p><p>{quizResult.attempt.feedback.explanation}</p><SourceLinks items={quizResult.attempt.feedback.resources} onSource={onSource} /></div>}</>}</section>
      <section className="demoStage"><h3>2. Attempt the programming assignment</h3><p>The supplied code contains one pointer-linking mistake. Hidden tests check empty and non-empty lists.</p>{!attempt && <button disabled={busy} onClick={() => action(async () => { const { data } = await api.post(`${API}/assignments/${demo.assignment_id}/attempts/`, {}); setAttempt(data.attempt); setCode(data.attempt.code); })}>Start demo assignment</button>}
        {attempt && <><label>Demo assignment code<textarea className="codeEditor" aria-label="Demo assignment code" value={code} onChange={e => setCode(e.target.value)} spellCheck={false} /></label><button disabled={busy || attempt.status !== "in_progress"} onClick={() => action(async () => { const { data } = await api.post(`${API}/attempts/${attempt.id}/`, { code, viva_answer: "The new node must link to the previous head before the head changes." }); setAttempt(data.attempt); })}>Run hidden checks</button>{attempt.test_score != null && <p className="practiceResult">Hidden-test score: {attempt.test_score}% · {attempt.test_score < 100 ? "Likely concept: preserve the previous head connection." : "All hidden checks passed. Mastery was updated."}</p>}
          <CoachingPanel key={attempt.id} assignmentAttemptId={attempt.id} onSource={onSource} onHint={() => updateDemo().catch(err => setError(errorText(err)))} />{attempt.status !== "in_progress" && attempt.test_score < 100 && <button disabled={busy} onClick={() => action(async () => { const { data } = await api.post(`${API}/assignments/${demo.assignment_id}/attempts/`, {}); setAttempt(data.attempt); setCode(demo.corrected_code); })}>Retry with teacher-allowed corrected example</button>}
        </>}
      </section>
      <section className="demoStage"><h3>3. Adaptive follow-up and reassessment</h3><button disabled={busy || attempt?.test_score !== 100} onClick={() => action(async () => { const data = await post(`courses/${demo.course.id}/practice/`, { topic_id: demo.topic_id }); setFollowup(data.question); setFollowupCode(data.question.starter_code); setFollowupResult(null); })}>Generate adaptive follow-up</button>{followup && <><h4>{followup.prompt}</h4><details open><summary>Why am I getting this question?</summary><p>{followup.reason}</p><SourceLinks items={followup.resources} onSource={onSource} /></details><label>Demo follow-up code<textarea aria-label="Demo follow-up code" className="codeEditor" value={followupCode} onChange={e => setFollowupCode(e.target.value)} /></label><button className="secondary" onClick={() => setFollowupCode(demo.followup_code)}>Use teacher-allowed demo example</button><button disabled={busy} onClick={() => action(async () => { setFollowupResult(await post(`questions/${followup.id}/attempts/`, { request_id: crypto.randomUUID(), code: followupCode })); })}>Complete adaptive follow-up</button>{followupResult && <p className="practiceResult">Follow-up score: {followupResult.attempt.score}% · Topic mastery {followupResult.mastery?.score}% ({followupResult.mastery?.state})</p>}</>}</section>
      {onReturnTeacher && <button onClick={onReturnTeacher}>Return to teacher evidence dashboard</button>}
    </>}
  </section>{teacher && demo && <><TeacherInsights key={demo.course.id} course={demo.course} revision={revision} onSource={onSource} /><EvaluationDashboard key={`evaluation-${demo.course.id}`} course={demo.course} onCompleted={() => updateDemo().catch(err => setError(errorText(err)))} /></>}{!teacher && !demo && <p>Your teacher can prepare an isolated demo learner. Your normal course data stays separate.</p>}</>;
}
