import { useEffect, useState } from "react";
import { get, errorText } from "./api";
import SourceLinks from "./SourceLinks";
import useLearningData from "./useLearningData";


export function LearningPath({ course, revision, onSource, onPractice }) {
  const { data, error } = useLearningData(course, "path", revision);
  return <section className="classroomBox"><p className="eyebrow">YOUR NEXT STEPS</p><h2>My Learning Path</h2><p>Recommended for today, based on your actual learning evidence. This path updates after assessments.</p>{error && <p role="alert">{error}</p>}{data ? <>{!data.tasks.length && <p>{data.topics.length ? "Your assessed topics are strong. Choose a consolidation question in Practice." : "Your teacher can add topics to start your path."}</p>}<div className="pathTasks">{data.tasks.map((task, index) => <article key={task.topic_id}><span className="taskNumber">0{index + 1}</span><div><p className="eyebrow">{task.prerequisite_weakness ? "PREREQUISITE FIRST" : "RECOMMENDED TODAY"}</p><h3>{task.topic}</h3><p>{task.reason}</p><SourceLinks items={task.resources} onSource={onSource} /><ol className="pathSteps">{task.steps.map(step => <li key={step}>{step}</li>)}</ol><button onClick={() => onPractice(task.topic_id)}>Practise {task.topic}</button><p className="nextTopic">Next: {task.next_topic}</p></div></article>)}</div><p className="methodNote">{data.method}</p></> : !error && <p role="status">Building your learning path…</p>}</section>;
}

export function MasteryMap({ course, revision, onSource, onPractice, studentId }) {
  const { data, error } = useLearningData(course, "path", revision, studentId);
  const [detail, setDetail] = useState(null), [detailError, setDetailError] = useState("");
  useEffect(() => { setDetail(null); }, [course?.id, revision, studentId]);
  async function open(topic) { setDetailError(""); try { setDetail(await get(`topics/${topic.topic_id}/`, studentId ? { params: { student_id: studentId } } : undefined)); } catch (err) { setDetailError(errorText(err)); } }
  const color = state => state === "Strong" ? "strong" : state === "Developing" ? "developing" : state === "Needs Practice" ? "needs" : "notStarted";
  return <section className="classroomBox"><p className="eyebrow">SEE YOUR UNDERSTANDING GROW</p><h2>Mastery Map</h2><p>{course.name} · Select a topic to inspect the evidence and relevant resources.</p>{error && <p role="alert">{error}</p>}{data?.topics.length > 0 && <CourseFlow topics={data.topics} onTopic={open} />}<div className="masteryGrid">{data?.topics.map(topic => <button key={topic.topic_id} className={`masteryTile ${color(topic.state)}`} aria-label={`${topic.topic} · ${topic.state} · ${topic.score}% mastery`} onClick={() => open(topic)}><svg viewBox="0 0 100 100" aria-label={`${topic.score}% mastery`}><circle cx="50" cy="50" r="40" className="ringTrack" /><circle cx="50" cy="50" r="40" className="ringValue" strokeDasharray={`${topic.score * 2.513} 251.3`} transform="rotate(-90 50 50)" /><text x="50" y="55" textAnchor="middle">{topic.state === "Not Started" ? "—" : `${Math.round(topic.score)}%`}</text></svg><strong>{topic.topic}</strong><span className="statusTag">{topic.state}</span><small>{topic.attempts} scored attempts</small>{!!topic.prerequisites.length && <small>Builds on: {data.topics.filter(t => topic.prerequisites.includes(t.topic_id)).map(t => t.topic).join(", ")}</small>}</button>)}</div>{detailError && <p role="alert">{detailError}</p>}
    {detail && <article className="topicEvidence"><h3>{detail.topic} · {detail.state}</h3><p>{detail.score}% mastery · Average hint level {detail.average_hint_level}</p><p className="methodNote">Learner model: {detail.model}. Unassessed knowledge is unknown.</p>{detail.history.length > 1 && <><svg className="masteryHistory" viewBox="0 0 500 130" role="img" aria-label={`Mastery history: ${detail.history.map(h => `${h.score}%`).join(', ')}`}><path d="M20 110H480 M20 10V110" fill="none" stroke="#b7ceca" /><polyline fill="none" stroke="#0b7866" strokeWidth="3" points={detail.history.map((h, i) => `${20 + 460 * i / (detail.history.length - 1)},${110 - h.score}`).join(" ")} />{detail.history.map((h, i) => <circle key={i} cx={20 + 460 * i / (detail.history.length - 1)} cy={110 - h.score} r="4" fill="#0b7866" />)}</svg><p>History: {detail.history.map(h => `${h.score}%`).join(" → ")}</p></>}
      <SourceLinks items={detail.resources} onSource={onSource} /><h4>Recent evidence and mistakes</h4><div className="rosterScroll"><table><thead><tr><th>Assessment</th><th>Score</th><th>Hint level</th><th>Concept to review</th></tr></thead><tbody>{detail.evidence.map(e => <tr key={e.id}><td>{e.kind}{!e.verified && " · provisional"}</td><td>{e.score ?? "Unscored"}</td><td>{e.hint_level}</td><td>{e.misconception || "No conceptual gap recorded"}</td></tr>)}</tbody></table></div><h4>Completed questions</h4>{detail.completed_questions.length ? <ul>{detail.completed_questions.map(q => <li key={q.id}>{q.prompt}</li>)}</ul> : <p>No completed adaptive questions yet.</p>}{onPractice && <button onClick={() => onPractice(detail.topic_id)}>Suggested next practice</button>}
    </article>}
  </section>;
}

export function CourseFlow({ topics, onTopic }) {
  const indexed = new Map(topics.map(t => [t.topic_id, t]));
  function depth(topic, seen = new Set()) { if (seen.has(topic.topic_id)) return 0; const next = new Set([...seen, topic.topic_id]); const parents = [...topic.prerequisites, ...(topic.parent_id ? [topic.parent_id] : [])].filter(id => indexed.has(id)); return parents.length ? 1 + Math.max(...parents.map(id => depth(indexed.get(id), next))) : 0; }
  const groups = new Map(); topics.forEach(topic => { const level = depth(topic); groups.set(level, [...(groups.get(level) || []), topic]); });
  const points = new Map(); let rows = 0;
  [...groups.keys()].sort((a, b) => a - b).forEach(level => { groups.get(level).forEach((topic, i) => points.set(topic.topic_id, { x: 10 + (i % 3) * 210, y: 10 + (rows + Math.floor(i / 3)) * 110 })); rows += Math.ceil(groups.get(level).length / 3); });
  const colors = { Strong: "#d9f4e6", Developing: "#e1edff", "Needs Practice": "#fff0dc", "Not Started": "#edf1f0" };
  return <div className="courseGraph"><svg viewBox={`0 0 640 ${Math.max(120, rows * 110)}`} role="img" aria-label="Course topics, subtopics and prerequisite relationships"><defs><marker id="course-arrow" markerWidth="8" markerHeight="8" refX="7" refY="3" orient="auto"><path d="M0,0 L0,6 L7,3 z" fill="#678d83" /></marker></defs>{topics.flatMap(topic => [...topic.prerequisites, ...(topic.parent_id ? [topic.parent_id] : [])].filter(id => points.has(id)).map(id => { const a = points.get(id), b = points.get(topic.topic_id); return <path key={`${id}-${topic.topic_id}`} d={`M${a.x + 95} ${a.y + 70} C${a.x + 95} ${a.y + 95},${b.x + 95} ${b.y - 25},${b.x + 95} ${b.y}`} fill="none" stroke="#678d83" strokeDasharray={id === topic.parent_id ? "4 3" : undefined} markerEnd="url(#course-arrow)" />; }))}{topics.map(topic => { const point = points.get(topic.topic_id); return <g key={topic.topic_id} role="link" tabIndex="0" aria-label={`View ${topic.topic} evidence`} onClick={() => onTopic(topic)} onKeyDown={e => { if (e.key === "Enter" || e.key === " ") { e.preventDefault(); onTopic(topic); } }} style={{ cursor: "pointer" }}><rect x={point.x} y={point.y} width="190" height="70" rx="12" fill={colors[topic.state]} stroke="#759d90" /><text x={point.x + 12} y={point.y + 27} fill="#173f35" fontSize="13">{topic.topic.length > 24 ? topic.topic.slice(0, 23) + "…" : topic.topic}</text><text x={point.x + 12} y={point.y + 50} fill="#37574e" fontSize="12">{topic.state}</text></g>; })}</svg><p className="methodNote">Arrows show prerequisites; dashed arrows connect topics to subtopics. Select a node to inspect its evidence.</p></div>;
}

export function ProgressReport({ course, revision, onSource, onPractice, studentId }) {
  const { data, error } = useLearningData(course, "report", revision, studentId);
  return <section className="classroomBox progressReport"><p className="eyebrow">EVIDENCE-BASED PROGRESS</p><h2>Learning Progress Report</h2>{error && <p role="alert">{error}</p>}{data ? <><h3>{data.student} · {data.course}</h3><p>{data.summary}</p><div className="statGrid"><Stat label="Programming average" value={data.programming.average_score == null ? "No attempts" : `${data.programming.average_score}%`} /><Stat label="Viva average" value={data.viva.average_score == null ? "No answers" : `${data.viva.average_score}%`} /><Stat label="Strong topics" value={data.strongest_topics.length} /><Stat label="Topics to practise" value={data.needs_practice.length} /></div><div className="classroomColumns"><div><h3>Strongest topics</h3><p>{data.strongest_topics.map(t => t.topic).join(", ") || "More independent evidence is needed."}</p><h3>Topics needing practice</h3><p>{data.needs_practice.map(t => `${t.topic} (${t.state})`).join(", ") || "No assessed topic currently needs practice."}</p></div><div><h3>Recent improvements</h3>{data.recent_improvements.map(t => <p key={t.topic}>{t.topic}: {t.from}% → {t.to}% (+{t.change} points)</p>)}{!data.recent_improvements.length && <p>Improvement will appear after multiple recorded assessments.</p>}<p>{data.viva.provisional_answers} viva answers have provisional feedback.</p></div></div><h3>Resources studied</h3><SourceLinks items={data.resources_studied.filter(r => r.source_id).map(r => ({ id: r.source_id, label: `${r.title}${r.page ? ` — Page ${r.page}` : r.slide ? ` — Slide ${r.slide}` : ""}` })).filter((r, i, arr) => arr.findIndex(s => s.id === r.id) === i)} onSource={onSource} /><p className="methodNote">{data.resource_note}</p><h3>Recommended next steps</h3>{data.next_steps.map(task => <article key={task.topic_id}><p>{task.reason}</p>{onPractice && <button className="secondary" onClick={() => onPractice(task.topic_id)}>Practise {task.topic}</button>}</article>)}<p className="methodNote">{data.method}</p><button className="secondary" onClick={() => window.print()}>Print progress report</button></> : !error && <p role="status">Preparing your progress report…</p>}</section>;
}

export function StudentDashboard({ course, revision, onNavigate }) {
  const { data, error } = useLearningData(course, "path", revision);
  return <><section className="learningHero"><p className="eyebrow">YOUR PERSONAL LEARNING COMPANION</p><h2>Understand. Practise. Make progress.</h2><p>Connect your teacher's explanations with hands-on programming and a path built around your learning.</p><div><button onClick={() => onNavigate("Ask LabTwin")}>Ask a course question</button><button className="secondary" onClick={() => onNavigate("Learning Path")}>My next steps</button></div></section>{error && <p role="alert">{error}</p>}{data?.diagnostic_recommended && <section className="classroomBox"><h2>Find your starting point</h2><p>Your knowledge has not been assessed yet. A short diagnostic helps LabTwin choose an appropriate explanation and practice level.</p><button onClick={() => onNavigate("Assessments")}>Take a diagnostic assessment</button></section>}{data && <><div className="statGrid"><Stat label="Strong topics" value={data.topics.filter(t => t.state === "Strong").length} /><Stat label="Developing" value={data.topics.filter(t => t.state === "Developing").length} /><Stat label="Needs practice" value={data.topics.filter(t => t.state === "Needs Practice").length} /><Stat label="Scored attempts" value={data.topics.reduce((sum, t) => sum + t.attempts, 0)} /></div><section className="classroomBox"><h2>Recommended next</h2>{data.tasks[0] ? <><h3>{data.tasks[0].topic}</h3><p>{data.tasks[0].reason}</p><button onClick={() => onNavigate("Learning Path")}>Open my learning path</button></> : <p>Choose a question from Practice or explore your course materials.</p>}</section></>}</>;
}

export function Stat({ label, value }) { return <div className="statCard"><strong>{value ?? "—"}</strong><span>{label}</span></div>; }
