import useLearningData from "./useLearningData";
import { useState } from "react";
import api from "../api";
import { base, errorText, get } from "./api";
import SourceLinks from "./SourceLinks";
import { SubmissionReview } from "../AssignmentsPanel";
import { Stat, MasteryMap, ProgressReport } from "./LearningViews";

export default function TeacherInsights({ course, revision = 0, onSource, dashboard = false }) {
  const [evidenceRevision, setEvidenceRevision] = useState(0), [record, setRecord] = useState(null), [recordError, setRecordError] = useState("");
  const { data, error } = useLearningData(course, "insights", revision + evidenceRevision);
  const [selected, setSelected] = useState(null), [student, setStudent] = useState(null), [downloadError, setDownloadError] = useState("");
  async function download() {
    try { const { data } = await api.get(`${base}/courses/${course.id}/insights/?format=csv`, { responseType: "blob" }); const url = URL.createObjectURL(data); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "labtwin-learning-evidence.csv"; anchor.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
    catch (err) { setDownloadError(errorText(err)); }
  }
  const rows = data?.evidence.filter(row => !selected || selected.support?.some(s => s.evidence_ids?.includes(row.id)) || selected.evidence_ids?.includes(row.id)) || [];
  async function inspectRecord(id) { setRecordError(""); try { setRecord(await get(`evidence/${id}/`)); } catch (err) { setRecordError(errorText(err)); } }
  return <><section className="classroomBox"><p className="eyebrow">SUPPORT EACH STUDENT WITH EVIDENCE</p><h2>{dashboard ? "Teacher Dashboard" : "Teacher AI Insights"}</h2><p>Class learning patterns, coding misconceptions and improvement, with the records behind each observation.</p>{error && <p role="alert">{error}</p>}{data ? <>
    <div className="statGrid"><Stat label="Enrolled students" value={data.enrolled_students} /><Stat label="Average attempts / topic" value={data.average_attempts} /><Stat label="Attempts using hints" value={data.hint_dependency == null ? "—" : `${data.hint_dependency}%`} /><Stat label="Assignment completion" value={data.assignment_completion.percent == null ? "—" : `${data.assignment_completion.percent}%`} /></div>
    <div className="insightsGrid"><div><h3>Supported observations</h3>{data.observations.length ? data.observations.map(insight => <button className="insightCard secondary" key={insight.id} onClick={() => setSelected(insight)}>{insight.text}<small>Inspect supporting data →</small></button>) : <p>Observations appear once students complete course assessments.</p>}</div><div><h3>Students needing support</h3>{data.students_needing_support.map(item => <button className="supportStudent secondary" key={item.student_id} onClick={() => setStudent(item.student_id)}><strong>{item.student}</strong><span>{item.topics.join(", ")}</span></button>)}{!data.students_needing_support.length && <p>No assessed student currently falls below the practice threshold.</p>}<h3>Viva performance</h3><p>{data.viva_performance.average_score ?? "—"}% average across {data.viva_performance.answers} answers. {data.viva_performance.provisional} are provisional estimates.</p></div></div>
    <div className="compactForm"><button className="secondary" onClick={() => setSelected({ text: "Source-based assessments", evidence_ids: data.assessment_performance.evidence_ids })}>Assessments: {data.assessment_performance.average_score ?? "—"}% across {data.assessment_performance.answers} answers · inspect</button><button className="secondary" onClick={() => setSelected({ text: "Programming results", evidence_ids: data.programming_performance.evidence_ids })}>Programming: {data.programming_performance.average_score ?? "—"}% across {data.programming_performance.attempts} attempts · inspect</button></div>
    <h3>Class mastery by topic</h3><div className="rosterScroll"><table><thead><tr><th>Topic</th><th>Mastery</th><th>Assessed / enrolled</th><th>Needs practice</th><th>Strong</th><th>Evidence</th></tr></thead><tbody>{data.topics.map(topic => <tr key={topic.id}><td>{topic.name}</td><td><div className="scoreBar"><span style={{ width: `${topic.average_mastery || 0}%` }} /></div>{topic.average_mastery == null ? "Unassessed" : `${topic.average_mastery}%`}</td><td>{topic.assessed_students} / {topic.enrolled_students}</td><td>{topic.needs_practice}</td><td>{topic.strong}</td><td><button className="secondary" onClick={() => setSelected({ text: topic.name, support: topic.support })}>Inspect</button></td></tr>)}</tbody></table></div>
    <h3>Common coding misconceptions</h3>{data.common_misconceptions.map((item, i) => <button key={i} className="insightCard secondary" onClick={() => setSelected(item)}>{item.concept}<small>{item.count} recorded attempts · inspect evidence</small></button>)}{!data.common_misconceptions.length && <p>No coding misconception has been recorded yet.</p>}
    <button onClick={download}>Export learning evidence CSV</button>{downloadError && <p role="alert">{downloadError}</p>}
    <p className="methodNote">{data.method}</p>
    {selected && <article className="insightSupport"><h3>Supporting data</h3><p>{selected.text || selected.concept}</p><button className="secondary" onClick={() => setSelected(null)}>Show all evidence</button>{selected.support?.map((row, i) => <p key={i}><button className="secondary" onClick={() => setStudent(row.student_id)}>{row.student}</button> {row.from != null ? `${row.from}% → ${row.to}%` : `${row.score}% · ${row.state}`} {row.resources_opened?.length ? `· Resources opened: ${row.resources_opened.join(', ')}` : ""}</p>)}</article>}
    <details open={!!selected}><summary>Retained assessment evidence</summary><div className="rosterScroll"><table><thead><tr><th>Student</th><th>Topic</th><th>Type</th><th>Score</th><th>Hints / attempt</th><th>Concept / status</th></tr></thead><tbody>{rows.map(row => <tr key={row.id}><td><button className="secondary" onClick={() => setStudent(row.student_id)}>{row.student}</button></td><td>{row.topic}</td><td>{row.kind}</td><td>{row.score ?? "—"}</td><td>{row.hint_level} / {row.attempt_number}</td><td>{row.misconception || "No gap recorded"}{!row.verified && " · provisional"}<small>Evidence #{row.id} · {new Date(row.created_at).toLocaleString()}</small><button className="secondary" onClick={() => inspectRecord(row.id)}>Inspect record</button></td></tr>)}</tbody></table></div></details>
  </> : !error && <p role="status">Loading class evidence…</p>}</section>{recordError && <p role="alert">{recordError}</p>}{record && (record.assignment_attempt ? <SubmissionReview key={record.id} report={record.assignment_attempt} onSaved={() => setEvidenceRevision(v => v + 1)} onClose={() => setRecord(null)} /> : <section className="classroomBox"><h3>{record.student} · {record.topic} · Evidence #{record.id}</h3><button className="secondary" onClick={() => setRecord(null)}>Close evidence</button><p>{record.prompt}</p>{record.code && <pre>{record.code}</pre>}<p className="sourceText">{record.answer}</p>{record.reason && <p>{record.reason}</p>}{record.feedback && <pre>{typeof record.feedback === "string" ? record.feedback : JSON.stringify(record.feedback, null, 2)}</pre>}<SourceLinks items={record.resources} onSource={onSource} />{record.tests && <details><summary>Teacher-only test evidence</summary><pre>{JSON.stringify(record.tests, null, 2)}</pre></details>}</section>)}{student && <><button className="secondary" onClick={() => setStudent(null)}>Close student learning review</button><MasteryMap key={`map-${student}`} course={course} revision={revision} studentId={student} onSource={onSource} /><ProgressReport key={`report-${student}`} course={course} revision={revision} studentId={student} onSource={onSource} /></>}</>;
}
