/* Run against the separate test-only server: node scripts/e2e_learning.cjs */
const { launchBrowser } = require('./e2e_browser.cjs');
const assert = require('node:assert/strict');
const { join } = require('node:path');
const fs = require('node:fs');
const origin = process.env.LABTWIN_E2E_URL || 'http://127.0.0.1:8000';

(async () => {
  const browser = await launchBrowser({ headless: true, ...(process.env.LABTWIN_E2E_CHROMIUM ? { executablePath: process.env.LABTWIN_E2E_CHROMIUM } : {}), args: ['--no-sandbox'] });
  const recording = process.env.LABTWIN_E2E_RECORD_DIR;
  const context = await browser.newContext({ acceptDownloads: true, viewport: { width: 1440, height: 1000 }, ...(recording ? { recordVideo: { dir: recording, size: { width: 1440, height: 1000 } } } : {}) });
  const page = await context.newPage();
  const began = Date.now(), captions = [];
  async function checkpoint(text) {
    if (!recording) return;
    captions.push({ start: (Date.now() - began) / 1000, text });
    await page.evaluate(text => { let box = document.getElementById('demo-recording-caption'); if (!box) { box = document.createElement('div'); box.id = 'demo-recording-caption'; box.style.cssText = 'position:fixed;bottom:14px;left:24px;right:24px;z-index:100000;padding:14px 20px;border-radius:10px;background:#0a2e29ed;color:white;font:18px/1.4 system-ui;box-shadow:0 4px 16px #0003;pointer-events:none'; document.body.appendChild(box); } box.textContent = text; }, text);
    console.log('Demo recording: ' + text);
    await page.waitForTimeout(9000);
  }
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  const nav = label => page.getByRole('navigation').getByRole('button', { name: label, exact: true }).click();
  try {
    await page.goto(origin);
    await page.getByRole('button', { name: 'New here? Create an account' }).click();
    await page.getByLabel('Your name', { exact: true }).fill('Hackathon Teacher');
    await page.getByLabel('Username', { exact: true }).fill(`learning-teacher-${Date.now()}`);
    await page.getByLabel('Password', { exact: true }).fill('Learning-Test-Password-92!');
    await page.getByLabel('I am a').selectOption('teacher');
    await page.getByRole('button', { name: 'Create account', exact: true }).click();
    await page.getByRole('heading', { name: 'Dashboard', exact: true }).waitFor();
    await checkpoint('1. A teacher creates a classroom and reuses existing LabTwin authentication.');
    await nav('Classes');
    await page.getByLabel('Class name', { exact: true }).fill('Multimodal Test Class');
    await page.getByLabel('Subject', { exact: true }).fill('Data Structures');
    await page.getByRole('button', { name: 'Create class', exact: true }).click();
    await page.locator('.joinCode').waitFor();
    await page.getByLabel('Classroom', { exact: true }).selectOption({ label: 'Multimodal Test Class' });
    await page.getByLabel('Course name', { exact: true }).fill('Data Structures Course');
    await page.getByRole('button', { name: 'Create course', exact: true }).click();
    await page.getByLabel('Current course', { exact: true }).selectOption({ label: 'Data Structures Course' });
    await checkpoint('2. Courses remain attached to classrooms. Student access is restricted to enrolled classrooms.');
    await nav('Course Materials');
    await page.getByLabel('New topic', { exact: true }).fill('Linked Lists');
    await page.getByRole('button', { name: 'Add topic', exact: true }).click();
    await page.getByLabel('Topic', { exact: true }).selectOption({ label: 'Linked Lists' });
    await page.getByLabel('Upload textbook, notes, slides or lecture').setInputFiles(join(__dirname, '../backend/labtwin/demo_assets/Data-Structures-Notes.pdf'));
    await page.getByRole('button', { name: 'Upload course material', exact: true }).click();
    await page.locator('.materialCard').filter({ hasText: 'Data-Structures-Notes.pdf' }).getByRole('button', { name: 'Explore material' }).waitFor({ timeout: 30000 });
    await page.getByRole('button', { name: 'Explore material', exact: true }).click();
    await page.getByLabel('Search within material', { exact: true }).fill('previous head');
    await page.getByRole('link', { name: /Source:.*Page 2/ }).first().click();
    await page.getByRole('dialog').getByText('VERIFIED COURSE SOURCE').waitFor();
    await page.getByRole('dialog').locator('iframe').waitFor();
    await checkpoint('3. A real PDF upload is automatically indexed. Citations open the exact source page.');
    await page.getByRole('button', { name: 'Close source', exact: true }).click();
    console.log('Course material and source viewer checks passed.');
    await nav('Demo Mode');
    await page.getByRole('button', { name: 'Prepare guided demo', exact: true }).click();
    await page.getByRole('button', { name: 'Enter isolated student demo', exact: true }).waitFor({ timeout: 30000 });
    assert.equal(await page.locator('.demoPanel .materialCard').count(), 3);
    await checkpoint('4. Demo Mode processes an original textbook PDF, slide deck and embedded-caption lecture into one knowledge base.');
    await page.getByRole('button', { name: 'Enter isolated student demo', exact: true }).click();
    await page.getByRole('button', { name: 'Ask demo question', exact: true }).click();
    await page.locator('.demoStage .answerCard .sourceLinks a').first().waitFor();
    const labels = await page.locator('.demoStage .answerCard .sourceLinks a').allTextContents();
    assert(labels.some(label => label.includes('Page'))); assert(labels.some(label => label.includes('Slide'))); assert(labels.some(label => /Lecture 4.*0:10/.test(label)));
    await checkpoint('5. Ask LabTwin retrieves course-backed information with page, slide and timestamp citations.');
    await page.getByRole('link', { name: /Source: Lecture 4/ }).first().click();
    await page.getByRole('dialog').locator('video').waitFor();
    await page.waitForFunction(() => { const video = document.querySelector('dialog video'); return video && video.readyState >= 1 && video.currentTime >= 10; });
    await checkpoint('6. The lecture citation seeks to the original timestamp. Embedded captions were extracted automatically; this fixture has no spoken narration.');
    await page.getByRole('button', { name: 'Close source', exact: true }).click();
    await page.getByRole('button', { name: 'Explain demo diagram', exact: true }).click();
    await page.getByText('new node points to previous head', { exact: false }).first().waitFor();
    await page.getByRole('link', { name: /Source: Linked Lists Slides/ }).last().click();
    await page.getByRole('dialog').locator('.sourceFigure img').waitFor();
    assert.equal(await page.getByRole('dialog').locator('.sourceFigure img').evaluate(image => image.complete && image.naturalWidth > 0), true);
    await checkpoint('7. Diagram understanding uses native connector relationships: new node points to previous head. The source figure is preserved.');
    await page.getByRole('button', { name: 'Close source', exact: true }).click();
    await page.getByRole('button', { name: 'Ask off-material question', exact: true }).click();
    await page.getByText('I could not find enough information', { exact: false }).waitFor();
    await checkpoint('8. Off-material questions are declined. LabTwin does not present outside knowledge as a course-backed answer.');
    await page.getByRole('button', { name: 'Start demo assessment', exact: true }).click();
    await page.locator('input[name="demo-quiz"]').first().check();
    await page.getByRole('button', { name: 'Submit demo assessment', exact: true }).click();
    await page.getByText('Assessment score: 100%', { exact: false }).waitFor();
    await checkpoint('9. A verified, source-cited diagnostic question records a real answer and updates the Bayesian learner model.');
    await page.getByRole('button', { name: 'Start demo assignment', exact: true }).click();
    await page.getByRole('button', { name: 'Run hidden checks', exact: true }).click();
    await page.getByRole('button', { name: 'Retry with teacher-allowed corrected example', exact: true }).waitFor();
    await checkpoint('10. The actual C program fails hidden checks. The likely concept is preserving the old head connection; private test cases remain hidden.');
    await page.getByRole('button', { name: 'Hint 1', exact: true }).click();
    await page.getByText('What must remain true before and after each update?', { exact: false }).waitFor();
    await page.getByRole('button', { name: 'Hint 2', exact: true }).click();
    await page.getByText('Focus on the order of updates', { exact: false }).waitFor();
    await checkpoint('11. Progressive hints move from an invariant to specific reasoning, with source recommendations.');
    await page.getByRole('button', { name: 'Retry with teacher-allowed corrected example', exact: true }).click();
    await page.getByRole('button', { name: 'Run hidden checks', exact: true }).click();
    await page.getByText('Hidden-test score: 100%', { exact: false }).waitFor();
    await page.getByRole('button', { name: 'Generate adaptive follow-up', exact: true }).click();
    await checkpoint('12. Successful retesting changes mastery. The follow-up explains why this question was selected. This demo teacher explicitly allows full examples.');
    await page.getByRole('button', { name: 'Use teacher-allowed demo example', exact: true }).click();
    await page.getByRole('button', { name: 'Complete adaptive follow-up', exact: true }).click();
    await page.getByText('Follow-up score: 100%', { exact: false }).waitFor();
    console.log('Guided demo code execution and reassessment passed.');
    await nav('Mastery Map');
    await page.getByRole('button', { name: /Linked Lists/ }).click();
    await page.locator('.masteryHistory').waitFor();
    await page.getByRole('heading', { name: 'Recent evidence and mistakes', exact: true }).waitFor();
    await checkpoint('13. The mastery map links prerequisites and subtopics. Clicking a topic exposes history, mistakes and source resources.');
    await nav('Learning Path');
    await page.getByRole('heading', { name: 'My Learning Path', exact: true }).waitFor();
    await nav('Assessments');
    await page.getByLabel('Assessment mode', { exact: true }).selectOption('diagnostic');
    await page.getByLabel('Assessment scope', { exact: true }).selectOption({ label: 'Linked Lists' });
    await page.getByLabel('Question format', { exact: true }).selectOption('short_answer');
    await page.getByLabel('Questions', { exact: true }).fill('1');
    await page.getByRole('button', { name: 'Start assessment', exact: true }).click();
    await page.getByLabel('Your short answer', { exact: true }).fill('A linked list');
    await page.getByRole('button', { name: 'Submit answer 1', exact: true }).click();
    await page.getByRole('heading', { name: 'Assessment report', exact: true }).waitFor();
    await checkpoint('14. Scoped MCQ, short-answer and numerical assessments provide cited feedback and post-assessment mastery reports.');
    await nav('Viva');
    await page.getByLabel('Viva topic', { exact: true }).selectOption({ label: 'Linked Lists' });
    await page.getByRole('button', { name: 'Start adaptive viva', exact: true }).click();
    await page.getByLabel('Your conceptual answer', { exact: true }).fill('Connect the new node to the previous head before updating the head pointer, preserving the linked chain.');
    await page.getByRole('button', { name: 'Save answer and continue', exact: true }).click();
    await page.getByText('Provisional estimate', { exact: false }).waitFor();
    await checkpoint('15. Viva asks follow-ups based on work and prior answers. Provisional feedback is available for teacher review; activity signals never prove cheating.');
    await nav('Progress');
    await page.getByRole('heading', { name: 'Learning Progress Report', exact: true }).waitFor();
    await page.getByText('topics with recorded improvement', { exact: false }).waitFor();
    await nav('Ask LabTwin');
    await page.getByLabel('Your question', { exact: true }).fill('Explain quantum entanglement');
    await page.getByRole('main').getByRole('button', { name: 'Ask LabTwin', exact: true }).click();
    await page.getByText('More material needed', { exact: true }).waitFor();
    await nav('My Courses');
    await page.locator('.materialCard').filter({ hasText: 'Lecture 4' }).getByRole('button', { name: 'Explore material', exact: true }).click();
    await page.getByLabel('Search within material', { exact: true }).fill('count');
    await page.getByRole('button', { name: 'Jump to timestamp', exact: true }).click();
    await page.waitForFunction(() => { const video = document.querySelector('.lectureDetail video'); return video && video.currentTime >= 30; });
    await page.getByRole('button', { name: 'Ask this lecture / material', exact: true }).click();
    await page.getByText('Asking this lecture:', { exact: false }).waitFor();
    await page.setViewportSize({ width: 390, height: 844 });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth + 1), false, 'Student page overflows mobile viewport');
    await page.getByRole('button', { name: 'Return to teacher', exact: true }).click();
    await nav('Demo Mode');
    await page.getByRole('button', { name: /student\(s\) improved in Linked Lists/ }).click();
    await page.getByRole('heading', { name: 'Supporting data', exact: true }).waitFor();
    await page.getByText('Demo Learner', { exact: true }).first().waitFor();
    const downloaded = page.waitForEvent('download');
    await page.getByRole('button', { name: 'Export learning evidence CSV', exact: true }).click();
    assert.equal((await downloaded).suggestedFilename(), 'labtwin-learning-evidence.csv');
    if (recording) await page.setViewportSize({ width: 1440, height: 1000 });
    await checkpoint('16. Teacher insights expose supporting student evidence, before/after mastery and CSV reports.');
    await page.getByRole('button', { name: 'Run evaluation', exact: true }).click();
    await page.getByText('DeepEval 4.2.7', { exact: false }).waitFor({ timeout: 120000 });
    await page.getByRole('heading', { name: 'Personalization across sessions', exact: true }).waitFor();
    await page.waitForFunction(() => document.querySelectorAll('.demoSteps li.complete').length === 17);
    if (recording) await page.getByRole('heading', { name: 'System Evaluation', exact: true }).evaluate(node => node.scrollIntoView({ block: 'start' }));
    await checkpoint('17. DeepEval actually executes the team benchmark and three four-session learner simulations. Offline metrics are labelled proxies; model-estimated gains are not claimed as causal human learning gains.');
    const evaluationDownload = page.waitForEvent('download');
    await page.getByRole('button', { name: 'Download evaluation evidence', exact: true }).click();
    assert.match((await evaluationDownload).suggestedFilename(), /^labtwin-evaluation-\d+\.json$/);
    if (recording) await page.getByRole('heading', { name: 'Personalization across sessions', exact: true }).evaluate(node => node.scrollIntoView({ block: 'start' }));
    await checkpoint('Personalization evidence grows across sessions. Next-answer prediction loss, model uncertainty, difficulty progression and repetition are computed from actual simulated responses. These are controlled experiments, not a human study.');
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth + 1), false, 'Teacher page overflows mobile viewport');
    await page.setViewportSize({ width: 1440, height: 1000 });
    if (!recording) await page.evaluate(() => scrollTo(0, 0));
    await page.mouse.move(0, 0);
    if (process.env.LABTWIN_E2E_SCREENSHOT) await page.screenshot({ path: process.env.LABTWIN_E2E_SCREENSHOT, fullPage: true });
    if (recording) { while ((Date.now() - began) / 1000 < 185) await page.waitForTimeout(5000); }
    assert.deepEqual(errors, []);
    console.log('PASS: multimodal upload/figures, citations, video seek, unsupported query, verified diagnostic/short answer/report, real failure/hints/retry, BKT/flow, adaptive follow-up, lecture search/viva/progress, teacher evidence/CSV, executed DeepEval/simulations/download and mobile layouts.');
  } catch (error) { await page.screenshot({path: '/tmp/labtwin-e2e-failure.png', fullPage: true}); console.error(await page.locator('body').innerText()); console.error(await page.locator('video').evaluateAll(nodes => nodes.map(v => ({ready: v.readyState, time: v.currentTime, error: v.error?.message, network: v.networkState})))); throw error; } finally {
    const video = page.video(); await context.close();
    if (recording && video) {
      const destination = join(recording, 'labtwin-track-d-demo.webm'); fs.renameSync(await video.path(), destination);
      const stamp = value => { const ms = Math.floor(value * 1000); return `${String(Math.floor(ms / 3600000)).padStart(2, '0')}:${String(Math.floor(ms / 60000) % 60).padStart(2, '0')}:${String(Math.floor(ms / 1000) % 60).padStart(2, '0')},${String(ms % 1000).padStart(3, '0')}`; };
      fs.writeFileSync(join(recording, 'labtwin-track-d-demo.srt'), captions.map((row, i) => `${i + 1}\n${stamp(row.start)} --> ${stamp(captions[i + 1]?.start ?? (Date.now() - began) / 1000)}\n${row.text}\n`).join('\n'));
    }
    await browser.close();
  }
})().catch(error => { console.error(error); process.exitCode = 1; });
