# Generated by Django 5.2.17 on 2026-09-30 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labtwin', '0002_attempt_hint_level_attempt_independent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=20)),
                ('question_id', models.CharField(blank=True, max_length=200)),
                ('question', models.TextField()),
                ('topic', models.CharField(default='General', max_length=200)),
                ('language', models.CharField(blank=True, max_length=40)),
                ('code', models.TextField(blank=True)),
                ('viva_answer', models.TextField(blank=True)),
                ('context', models.JSONField(default=dict)),
                ('test_results', models.JSONField(default=list)),
                ('result', models.JSONField(default=dict)),
                ('status', models.CharField(default='processing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='labtwin.studentprofile')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
