# Generated by Django 6.0.8 on 2026-09-30 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labtwin', '0004_classrooms_and_accounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('instructions', models.TextField()),
                ('language', models.CharField(default='Python', max_length=10)),
                ('tests', models.JSONField(default=list)),
                ('viva_question', models.TextField(blank=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('allow_paste', models.BooleanField(default=True)),
                ('require_screen', models.BooleanField(default=False)),
                ('require_camera', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='labtwin.classroom')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(blank=True)),
                ('viva_answer', models.TextField(blank=True)),
                ('test_results', models.JSONField(default=list)),
                ('test_score', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(default='in_progress', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('teacher_score', models.FloatField(blank=True, null=True)),
                ('teacher_feedback', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='labtwin.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_attempts', to='labtwin.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='LiveConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.JSONField(default=dict)),
                ('answer', models.JSONField(default=dict)),
                ('track_sources', models.JSONField(default=dict)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labtwin.account')),
            ],
        ),
        migrations.CreateModel(
            name='IceCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=10)),
                ('value', models.JSONField(default=dict)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='labtwin.liveconnection')),
            ],
        ),
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('screen_active', models.BooleanField(default=False)),
                ('camera_active', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='live_session', to='labtwin.assignmentattempt')),
            ],
        ),
        migrations.AddField(
            model_name='liveconnection',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='labtwin.livesession'),
        ),
        migrations.CreateModel(
            name='MonitoringEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=64)),
                ('kind', models.CharField(max_length=40)),
                ('stage', models.CharField(default='coding', max_length=10)),
                ('detail', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='labtwin.assignmentattempt')),
            ],
        ),
        migrations.AddConstraint(
            model_name='assignmentattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'in_progress')), fields=('assignment', 'student'), name='one_active_assignment_attempt'),
        ),
        migrations.AddConstraint(
            model_name='monitoringevent',
            constraint=models.UniqueConstraint(fields=('attempt', 'event_id'), name='unique_monitoring_event'),
        ),
    ]
