# Generated by Django 6.0.8 on 2026-09-30 16:21

import django.db.models.deletion
import labtwin.learning_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labtwin', '0006_assignment_allow_solution_assignment_starter_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetopic',
            name='concepts',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='coursetopic',
            name='learner_parameters',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='coursetopic',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtopics', to='labtwin.coursetopic'),
        ),
        migrations.AddField(
            model_name='coursetopic',
            name='taxonomy_evidence',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='practiceattempt',
            name='feedback',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='practicequestion',
            name='explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='practicequestion',
            name='fingerprint',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='practicequestion',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='practicequestion',
            name='semantic_vector',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='practicequestion',
            name='verification',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='practicequestion',
            name='verification_status',
            field=models.CharField(default='legacy', max_length=40),
        ),
        migrations.AddField(
            model_name='questionbankitem',
            name='explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='questionbankitem',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='sourceunit',
            name='analysis_method',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='sourceunit',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sourceunit',
            name='concepts',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='sourceunit',
            name='content_type',
            field=models.CharField(default='text', max_length=30),
        ),
        migrations.AddField(
            model_name='sourceunit',
            name='prerequisite_names',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='sourceunit',
            name='subtopic',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sourceunit',
            name='visual_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sourceunit',
            name='visual_file',
            field=models.FileField(blank=True, storage=labtwin.learning_models.private_learning_storage, upload_to=labtwin.learning_models.visual_path),
        ),
        migrations.AddField(
            model_name='topicmastery',
            name='knowledge_probability',
            field=models.FloatField(default=0.35),
        ),
        migrations.AddField(
            model_name='topicmastery',
            name='model_parameters',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='topicmastery',
            name='model_version',
            field=models.CharField(default='legacy-weighted-v1', max_length=40),
        ),
        migrations.CreateModel(
            name='AssessmentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(default='quiz', max_length=30)),
                ('scope', models.JSONField(default=dict)),
                ('status', models.CharField(default='in_progress', max_length=30)),
                ('report', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labtwin.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='labtwin.studentprofile')),
            ],
        ),
        migrations.AddField(
            model_name='practicequestion',
            name='assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='labtwin.assessmentsession'),
        ),
        migrations.CreateModel(
            name='EvaluationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='queued', max_length=30)),
                ('mode', models.CharField(default='deterministic', max_length=30)),
                ('framework', models.CharField(default='DeepEval', max_length=60)),
                ('dataset_version', models.CharField(blank=True, max_length=100)),
                ('results', models.JSONField(default=dict)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='labtwin.course')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_runs', to='labtwin.account')),
            ],
        ),
    ]
