# Generated by Django 6.0.8 on 2026-10-01 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labtwin', '0007_final_track_d'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='camera_cues_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='camera_eye_closure',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='camera_cues_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='camera_eye_closure',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AssessmentCameraEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=64)),
                ('kind', models.CharField(max_length=40)),
                ('detail', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camera_events', to='labtwin.assessmentsession')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='labtwin.practicequestion')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('assessment', 'event_id'), name='unique_assessment_camera_event')],
            },
        ),
    ]
