# Generated by Django 6.0.8 on 2026-10-03 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labtwin', '0008_assessment_camera'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialprocessjob',
            name='completed_units',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='materialprocessjob',
            name='heartbeat_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materialprocessjob',
            name='lease_token',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='materialprocessjob',
            name='stage',
            field=models.CharField(default='queued', max_length=40),
        ),
        migrations.AddField(
            model_name='materialprocessjob',
            name='total_units',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='materialprocessjob',
            name='unit_label',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
