# Generated by Django 6.0.8 on 2026-10-06 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labtwin', '0009_material_processing_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(db_index=True)),
                ('code_digest', models.CharField(max_length=64)),
                ('state_digest', models.CharField(max_length=64)),
                ('issued_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_otp', to='labtwin.account')),
            ],
        ),
    ]
