# Generated by Django 6.0.8 on 2026-10-07 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labtwin', '0010_password_reset_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveryPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=16, unique=True)),
                ('verified_at', models.DateTimeField()),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_phone', to='labtwin.account')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('bind', 'Bind phone'), ('reset', 'Reset password')], max_length=10)),
                ('request_id', models.UUIDField(unique=True)),
                ('number', models.CharField(max_length=16)),
                ('state_digest', models.CharField(max_length=64)),
                ('verification_sid', models.CharField(blank=True, max_length=34)),
                ('status', models.CharField(default='queued', max_length=10)),
                ('issued_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_challenges', to='labtwin.account')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('account', 'purpose'), name='unique_phone_otp_purpose')],
            },
        ),
    ]
